{% set version = "3.2.1" %}

package:
  name: gsw
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: a0a34c2f5a616bfbec9427522f9974b9a9b6589ae2a0af8723927fba6b07c6cc

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*
  run:
    - python
    - numpy >=1.11

test:
  imports:
    - gsw

about:
  home: https://github.com/TEOS-10/GSW-Python/
  license: MIT
  license_file: LICENSE
  summary: 'Gibbs SeaWater Oceanographic Package of TEOS-10'

extra:
  recipe-maintainers:
    - efiring
    - ocefpaf
