{% set version = "3.0.6" %}

package:
  name: gsw
  version: {{ version }}

source:
  fn: gsw-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/gsw/gsw-{{ version }}.tar.gz
  sha256: ffe8496c61bb3cf488316f6444234a69f7cd6884fb04ff7b4889a773fbed4f44

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - gsw

about:
  home: https://github.com/TEOS-10/python-gsw/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Gibbs SeaWater Oceanographic Package of TEOS-10.'

extra:
  recipe-maintainers:
    - ocefpaf
