travis:
  secure:
    BINSTAR_TOKEN: NMSXRk47bM+zk4gBwC9zKYA4vHe6No3YwCKhUd7eZ0f1CEIPxRyimQjy4jpakGPhQeOXp8DyVq2+bHNLV/8M/A9OZwS+7cVK3y0i3+UfEWz2oJljFhkM53c84xqj6JFZ+o5d9R+0LpIKncD0o8g2aVRbcAbp7b1cNxJf/XuK3nCY4saDjpdeAzTqzPgW6W451b7tEJlJ/+03gRokSGHhuDtvdCmVu8ngKLjOYCnlw4KkvXBufjTH+4IBxtqIP3h0tTFDAMr2+mMjwMyoKgFQD4s07fbatb8bFjlBfzLz/kpSQ+5RqLlgufFXqHuVhTtqDkBNTM3QohIiY2R+K+xZ6EpPNd294zyHJ72Er/iypLgUNk0b6N/Y4nQ5oHn9i3+KPBDUR1+gh9Q5d89FZD3FYXLCef3PUtAOKMUJTkhPtSUSO/lzH15N/aceKqN8mLdQq1P36rMlbmvL0yoGBxSGVWjUcRvHFaPCINAeH6m0rnUL2T7bu1KfO3ZYbG+yq4YrOkcyLSURnDLZQhVdlCw1rj2lkUHgtyTELmn9bpQpYx9UoeaCFEy0bvhw9THtbLhZ3Qi+rbz+zh+blHg+wAZxX46Xsft9y2a2l3/tUwH74hKl5t2QfZIIH7RC3agccVoYmX8P7rZmhE/Gbe+QX9QwQjI+vr+GouYJSZvep0ACR/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
