travis:
  secure:
    BINSTAR_TOKEN: czgVEWX3WNln3aM0soLSe6PY1twZtZQPtYI74aoXOwDw71hiBzvcPn0ySVJ6KMh5KYpOTDBx1L3tqsqBlGe6TmuBkbea1HVfA4ZESAulUDHc9JmBsWkMS6hGT+izGHDL//vA629sps63fa+0sTTw3pOgfCIQy3fpuvbPz763PFQQWBHuzGazYi2Zq7xO6F1bVSorn7j6O78uggPosRdFthCUHHWJfU2588sTWUFHrS8EW7qFOel1v0evka0qzd0G78gY/oNdsTh2E3BTrImwqT/30Jb6XEAFgtgbNdWXLR49xigVyCxiW5RBrLiD8MTTZcb9oDfGeOM53mzB/MYhKtMyXQFJnD09Rn4M6XT1Pvnqsqsr7Ge1YHqlomxJQSS0X4g7CkUtUfmDlDVpWlAXYDmBPQ0Uo7PG83p/sfiEwWIDOiHQBXzkbK1vBUn+blRnkLYO/7HWweQTun4cK477tvti5HfAUpXdAtm84Bzx+XD8GCdtfuJMhcj/+SS/2aXWu4f9bIst2eeeClWn8mJlqik81EIxhgzq5ThxpP1pGB7xpM3WDK2e39mHMzEukww3b4jALF2MUgJplXuZ065T3W3Lb+Fx37GicNDJdy5brc52NRtjTo+CXpsbVwBfhDp/UeeK7wljb/1AYoWsdY9LDoVMEEiJzvpGkhZfoYkpr3A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
