travis:
  secure:
    BINSTAR_TOKEN: hzyM6KAho0HJLhDHhCVAXtJu+XTSU9/W4HuH7sbqPMk/7OZP0A3OT3DsXUy9nrrWyyTFfcwXKW4VwFciQ88va2H+7qOVAdjV/VLqoUUXMaWeZQiGzk8cR9yGxe2IdffqqD4iarnnxrlWqtbOSNc+qbZf2Lnq3YsTw1AZRiuDd2L5LiBf5Mse+vUGdY7Xlhrunw3yeDToLdHRCblqW1tvzKsUWGDFFpfM8f87MsrS38d+nltLhRTicZkOHNJjnaU6f7Zln3sJJLE4iS2ZiAkm7Qf2AI9PwdnD17+KRKQ7vz1i5YYOUfTXW5Tn/o4hFq3T+zGfsa6m4ovu6vdw/mB5cRFEza0No0Is51JKpCM+KyF+UOu9d+eISSl0hsrp6tUXkHTfpeqlGTw+fJBTWu+1ZZyRz5daaJIl/cQi7RC8hIojQlp1YKr3qnvnLTaS65jUpJeUYJIDvrjfu1tw5WZZndQ6BYIZ37aOdwzpwOdO9megtEXb2+U8KqR5DkpIkUFDCx370wPnKgjJvS9BraPaqZ0e43dVA/TXr5WgamCP+L3nlY/6sAOZnx0Qda0Lfogl/dMxC49jDi4OutqXmGNSkzVBKEhaMtya4FkN2FYc6ViYt6ZWiLyKqzh3YyZ4qBSxVz8TQ/6LwvNw7AhG2XTieADjYe2FGdNPIYaK0FaEnSw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
